steps:
  - imports:
      align: group
      long_list_align: inline
      separate_lists: false
  - language_pragmas:
      style: vertical
      align: false
  - trailing_whitespace: {}
# columns: 80
language_extensions:
  - ExplicitNamespaces
