name: cv

ghc-options: -Wall -Werror

library:
  source-dirs: lib

executables:
  cv:
    dependencies:
      - cv
    main: Main.hs

dependencies:
  - base
  - blaze-html
  - bytestring
  - directory
  - filepath
  - process
  - shakespeare
  - temporary
  - text

default-extensions:
  - StrictData
